### PR TITLE
New methods to add custom regex, matching to existing or new tags

### PR DESCRIPTION
**Pull request by OClement**
Hi @sanjayaksaxena 
I am thinking of using your library to help us parse strings in order to replace some specific "tags" to images (custom emoticons). It would help tremendously in cutting the amount of code I'd need to write, but since your library doesn't cover all the possible strings I'd need, I took the liberty to fork and extend it a little bit.

The idea is to be able to add custom regexes that will map to an existing `tag` (or create a new one at the same time a regex is added). I added some JSDoc and updated the tests accordingly (still 100% coverage)

Thank you for your time!

### CODE REVIEW

**Comment by sanjayaksaxena** [comment]
Hi @OClement 

Many thanks for your contribution! 

Please allow us some time for review & impact analysis before we can merge the PR.

Best,
Sanjaya

**Review by sanjayaksaxena — APPROVED** [review]
Hi @OClement,

Thanks for your patience. We just completed the impact analysis and will need to ensure the following:

1. `addRegex()` documentation clearly mentions that the added regex will supersede the internal parsing;
2. call to `defineConfig()` will reset the effect of any previous call to `addRegex()`;

AND modify `defineConfig()` to also reset the finger print codes to the original configuration (incl test cases for this change).

We are going ahead with the PR and will make the above changes before releasing it on NPM.

Best,
Sanjaya

**Comment by sanjayaksaxena** [comment]
Hi @OClement,

Just wanted to share that the new version has been released on NPM incorporating the above changes.

Best,
Sanjaya

**Comment by OClement** [comment]
Great news!

Thanks for your work!

**Pull request merged**
